### PR TITLE
Change to Williams problems

### PR DESCRIPTION
**Pull request by tuncbkose**

### CODE REVIEW

**Comment by tuncbkose** [comment]
@FabsOliveira In lecture 7, I'm not sure what is the best way of dealing with the impossible routes. 

In the problem (p.274), stuff is being distributed from factories to depots and cities, and some routes in between that are not usable. In code, so far I've represented this with using missing values, and replacing them/filtering them out appropriately. In the explicitly written out model in lec 5, I just omitted those variables from the objective for example. I'm not sure what would be the best way to write the summarized symbolic formulation model though.

Do you have any suggestions?

**Comment by FabsOliveira** [comment]
> @FabsOliveira In lecture 7, I'm not sure what is the best way of dealing with the impossible routes.
> 
> In the problem (p.274), stuff is being distributed from factories to depots and cities, and some routes in between that are not usable. In code, so far I've represented this with using missing values, and replacing them/filtering them out appropriately. In the explicitly written out model in lec 5, I just omitted those variables from the objective for example. I'm not sure what would be the best way to write the summarized symbolic formulation model though.
> 
> Do you have any suggestions?

We should control the domain of the variables and constraints accordingly. Say we have a parameter $A_{ij}$ indicating (i.e., $A_{ij}=1$) for which arcs $(i,j)$ the flow variable $x_{ij}$ and a capacity constraint (flow capacity equals $C_{ij}$) should be created. Then, we would have
$$
x_{ij} \le C_{ij}, \forall (i,j) ~:~ A_{ij} = 1.
$$
and the variable creation would be conditioned as
$$
x_{ij} \ge 0, \forall (i,j) ~:~ A_{ij} = 1.
$$

To do that in JuMP, you just have to impose conditions in the domain of the variable / constraint, e.g.,

```{julia}
I = 1:N_I   # number of elements in I 
J = 1:N_J   # " in J
@variable(model, x[i in I, j in J; A[i,j]==1])
```

The same logic applies to constraint generation.

**Comment by tuncbkose** [comment]
I was for some reason reluctant to add conditional constraints like that but if you say it's no problem, I have no problem. I'll update accordingly.

**Comment by FabsOliveira** [comment]
There is an important point to be made there. In practice, most models require conditional variable and constraint generation to avoid inadvertent bounds (say forcing a capacity to be zero when there is no capacity but the matrix C had 0 entry for it) or preemptively reducing the model size (which can help in large models since resolve only applies after the potentially massive model has been already generated)

**Comment by tuncbkose** [comment]
Are conditional variables the best way to do this actually? Because doing so breaks iterating through them using `i in 1:I, j in 1:J` without the conditional part again, and it also prevents doing stuff like matrix multiplication or element-wise multiplication, i.e.
```julia
fac2dep = [0.5 0.5 1.0 0.2;
           0.0 0.3 0.5 0.2]
@variable(model, x[i in 1:I, j in 1:J; fac2dep[i,j]>0.0] >= 0)
@constraint(model, sum(fac2dep.*x) <= some_limit)
```
doesn't seem possible.

I wonder if the benefit of having less variables in the model outweigh the costs. For example, I don't know if computing something like
```julia
@constraint(model, sum(if (fac2dep[i,j] > 0) fac2dep[i,j]*x[i,j] else 0 end for i in 1:I, j in 1:J) <= some_limit)
```
is as efficient as a matrix multiplication would be.

So I imagine it is either more less variables but possibly more efficient computation, or more variables (and constraints to set them to 0 probably) but more efficient code.

**Comment by tuncbkose** [comment]
Sure it is not matrix multiplication here, but I expect it probably will be when it goes to the solver.

**Comment by tuncbkose** [comment]
How about [JuMP.fix](https://jump.dev/JuMP.jl/stable/api/JuMP/#fix)?

**Comment by FabsOliveira** [comment]
JuMP.fix is to fix decision variables to values, which is slightly different from telling the solver that a variable must (or must not) be created for a certain combination of indices. Not sure what you have in mind though

**Comment by tuncbkose** [comment]
Sorry, what I have in mind is to declare variables as
```julia
@variable(model, x[1:I,1:J] >= 0)
```
without if's, so that the shapes are nice, the fix them to zero for invalid routes, like
```julia
fac2dep = [0.5 0.5 1.0 0.2;
           0.0 0.3 0.5 0.2]
fix.(x[findall(iszero, fac2dep)], 0.0; force=true)
```

**Pull request merged**
